package daemon

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// ReportLevel indicates severity of a report.
type ReportLevel string

const (
	LevelInfo     ReportLevel = "info"
	LevelWarn     ReportLevel = "warn"
	LevelCritical ReportLevel = "critical"
)

// ReportType classifies the kind of report.
type ReportType string

const (
	TypeAlert ReportType = "alert"
	TypeDaily ReportType = "daily"
	TypeWeekly ReportType = "weekly"
)

// Report is a structured notification generated by the daemon.
type Report struct {
	Title   string      `json:"title"`
	Type    ReportType  `json:"type"`
	Summary string      `json:"summary"`
	Details string      `json:"details"`
	Level   ReportLevel `json:"level"`
}

// Reporter handles writing reports to disk and bridging to external systems.
type Reporter struct {
	logDir  string
	bridge  string
}

// NewReporter creates a reporter that writes into the daemon log directory.
func NewReporter(logDir string) *Reporter {
	return &Reporter{logDir: logDir, bridge: ""}
}

// SetBridge configures an external report bridge destination.
func (r *Reporter) SetBridge(target string) {
	r.bridge = target
}

// Send writes a report to the @daemon/reports/ directory as a markdown file.
func (r *Reporter) Send(report Report) error {
	dir := filepath.Join(r.logDir, "reports")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("reporter: mkdir: %w", err)
	}

	filename := fmt.Sprintf("%s-%s.md",
		time.Now().Format("2006-01-02-150405"),
		strings.ReplaceAll(strings.ToLower(report.Title), " ", "-"),
	)
	path := filepath.Join(dir, filename)

	content := fmt.Sprintf("# %s\n\n**Type:** %s | **Level:** %s | **Date:** %s\n\n## Summary\n\n%s\n\n## Details\n\n%s\n",
		report.Title, report.Type, report.Level,
		time.Now().Format(time.RFC3339),
		report.Summary, report.Details,
	)

	return os.WriteFile(path, []byte(content), 0644)
}

// SendToBridge forwards a report to the configured external bridge.
func (r *Reporter) SendToBridge(report Report) error {
	if r.bridge == "" {
		return fmt.Errorf("reporter: no bridge configured")
	}
	// In production this would POST/stream to the bridge endpoint.
	_ = report
	return nil
}

// GenerateDailySummary creates a daily rollup report and sends it.
func (r *Reporter) GenerateDailySummary(activeAgents, totalAgents int, tokensUsed int) Report {
	report := Report{
		Title:   "Daily Summary",
		Type:    TypeDaily,
		Level:   LevelInfo,
		Summary: fmt.Sprintf("Active agents: %d/%d. Tokens used today: %d.", activeAgents, totalAgents, tokensUsed),
		Details: fmt.Sprintf("Report generated at %s by agent-os daemon.\n\n- Active agents: %d\n- Total agents: %d\n- Token usage: %d\n",
			time.Now().Format(time.RFC3339), activeAgents, totalAgents, tokensUsed),
	}
	_ = r.Send(report)
	return report
}

