// Package workspace provides the agent workspace subsystem: isolated
// directories for agent home, scratch, artifacts, memory, and team
// collaboration, all backed by physical storage under a configurable
// base path.
package workspace

import "time"

// WorkspaceID is a short identifier for a workspace.
type WorkspaceID string

// AgentID identifies an agent.
type AgentID string

// WorkspaceType classifies the purpose of a workspace.
type WorkspaceType string

const (
	TypeAgent WorkspaceType = "agent"
	TypeTeam  WorkspaceType = "team"
	TypeTemp  WorkspaceType = "temp"
)

// WorkspaceStatus indicates the lifecycle stage of a workspace.
type WorkspaceStatus string

const (
	StatusActive   WorkspaceStatus = "active"
	StatusArchived WorkspaceStatus = "archived"
	StatusDeleted  WorkspaceStatus = "deleted"
)

// WorkspaceStorage tracks resource usage within a workspace.
type WorkspaceStorage struct {
	UsedBytes  int64 `json:"used_bytes"`
	UsedFiles  int   `json:"used_files"`
	LimitBytes int64 `json:"limit_bytes"`
}

// WorkspaceConfig holds tunable settings for a workspace.
type WorkspaceConfig struct {
	MaxArtifacts int               `json:"max_artifacts"`
	MaxCacheSize int64             `json:"max_cache_size"`
	TTL          string            `json:"ttl"`
	Labels       map[string]string `json:"labels,omitempty"`
}

// Workspace is the core data structure representing an isolated agent
// or team work area on disk.
type Workspace struct {
	ID        WorkspaceID      `json:"id"`
	OwnerID   string           `json:"owner_id"`
	Type      WorkspaceType    `json:"type"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	Status    WorkspaceStatus  `json:"status"`
	Storage   WorkspaceStorage `json:"storage"`
	Config    WorkspaceConfig  `json:"config"`
}

// AgentProfile describes the personality and preferences of an agent.
type AgentProfile struct {
	Name            string   `json:"name"`
	Language        string   `json:"language"`
	PreferredModel  string   `json:"preferred_model"`
	PreferredSkills []string `json:"preferred_skills,omitempty"`
	Style           string   `json:"style"` // balanced, minimal, verbose, opinionated
}

// ProfileStyle constants.
const (
	StyleBalanced    = "balanced"
	StyleMinimal     = "minimal"
	StyleVerbose     = "verbose"
	StyleOpinionated = "opinionated"
)

// ArtifactType classifies the kind of artifact.
type ArtifactType string

const (
	ArtifactDiff   ArtifactType = "diff"
	ArtifactReport ArtifactType = "report"
	ArtifactCode   ArtifactType = "code"
	ArtifactImage  ArtifactType = "image"
	ArtifactLog    ArtifactType = "log"
)

// Artifact is a persisted work product generated by an agent.
type Artifact struct {
	Name      string       `json:"name"`
	Type      ArtifactType `json:"type"`
	Content   string       `json:"content"`
	CreatedAt time.Time    `json:"created_at"`
	Size      int64        `json:"size"`
}

// DecisionStatus tracks whether a team decision is still in effect.
type DecisionStatus string

const (
	DecisionActive      DecisionStatus = "active"
	DecisionSuperseded  DecisionStatus = "superseded"
	DecisionReverted    DecisionStatus = "reverted"
)

// Decision records a team-level architectural or process choice.
type Decision struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Context   string         `json:"context"`
	Decision  string         `json:"decision"`
	Reasoning string         `json:"reasoning"`
	MadeBy    AgentID        `json:"made_by"`
	Timestamp time.Time      `json:"timestamp"`
	Status    DecisionStatus `json:"status"`
}

// SharedContext holds team-wide contextual information that all members
// can reference.
type SharedContext struct {
	CurrentGoal    string   `json:"current_goal"`
	Architecture   string   `json:"architecture"`
	Conventions    []string `json:"conventions,omitempty"`
	ActiveBranches []string `json:"active_branches,omitempty"`
}
